name: Prueba Unitaria y Despliegue

on:
  push:
    branches:
      - main  # Reemplaza "main" con el nombre de tu rama principal

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar pruebas
      run: npm test

- name: Publicar pagina
        run: surge --project ./ --domain ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_API_KEY }}